import AVKit
import SwiftUI

/// Full-screen video player for lecture videos generated by Veo.
struct VideoPlayerView: View {
    let url: URL
    @Environment(\.dismiss) private var dismiss
    @State private var player: AVPlayer?

    var body: some View {
        // Our controls sit in their own bar above the player rather than
        // overlaying it. AVKit claims both top corners inside the player's
        // own bounds — AirPlay at the leading edge, volume/mute at the
        // trailing edge — so anything overlaid there gets covered whenever
        // the playback controls fade in. Giving the player a shorter box
        // moves its chrome down with it. Portrait 9:16 footage is
        // letterboxed anyway, so the video itself doesn't shrink.
        VStack(spacing: 0) {
            HStack(spacing: 8) {
                Spacer()

                // Share sheet — covers Save Video (Photos), Save to Files,
                // AirDrop, Messages, etc.
                ShareLink(
                    item: url,
                    preview: SharePreview("Lecture Video")
                ) {
                    Image(systemName: "square.and.arrow.up.circle.fill")
                        .font(.system(size: 30))
                        .symbolRenderingMode(.hierarchical)
                        .foregroundStyle(.white.opacity(0.85))
                        .frame(width: 44, height: 44)
                        .contentShape(Rectangle())
                }

                Button {
                    player?.pause()
                    dismiss()
                } label: {
                    Image(systemName: "xmark.circle.fill")
                        .font(.system(size: 30))
                        .symbolRenderingMode(.hierarchical)
                        .foregroundStyle(.white.opacity(0.85))
                        .frame(width: 44, height: 44)
                        .contentShape(Rectangle())
                }
                .accessibilityLabel("Close")
            }
            .padding(.horizontal, 12)
            .padding(.bottom, 4)

            ZStack {
                if let player {
                    VideoPlayer(player: player)
                } else {
                    Color.black
                    ProgressView()
                        .tint(.white)
                }
            }
        }
        .background(Color.black.ignoresSafeArea())
        .statusBarHidden()
        .onAppear {
            let avPlayer = AVPlayer(url: url)
            self.player = avPlayer
            avPlayer.play()
        }
        .onDisappear {
            player?.pause()
            player = nil
        }
    }
}
