import SwiftUI
import CoreText

@main
struct RecallTutorApp: App {
    @State private var chatModel = ChatModel()

    init() {
        Self.registerBundledFonts()
    }

    /// The Info.plist is generated by Xcode (no UIAppFonts entry), so the
    /// bundled Libre Baskerville faces are registered at launch instead.
    private static func registerBundledFonts() {
        for name in ["LibreBaskerville", "LibreBaskerville-Italic", "Baskervville", "Baskervville-Italic"] {
            guard let url = Bundle.main.url(forResource: name, withExtension: "ttf")
                ?? Bundle.main.url(forResource: name, withExtension: "ttf", subdirectory: "Fonts")
            else {
                assertionFailure("Missing bundled font \(name).ttf")
                continue
            }
            CTFontManagerRegisterFontsForURL(url as CFURL, .process, nil)
        }
    }

    var body: some Scene {
        WindowGroup {
            ChatView()
                .environment(chatModel)
                .preferredColorScheme(.light)
        }
    }
}
