import SwiftUI
import CoreText
import FirebaseCore

@main
struct RecallTutorApp: App {
    @State private var chatModel: ChatModel

    init() {
        Self.registerBundledFonts()
        // Firebase powers the built-in tutor (Google sign-in + managed Gemini).
        // Only configure when the app ships a GoogleService-Info.plist — the
        // app runs fine without it in bring-your-own-key mode (see FIREBASE.md).
        // Must happen before ChatModel() so provider detection sees Firebase.
        if Bundle.main.url(forResource: "GoogleService-Info", withExtension: "plist") != nil {
            FirebaseApp.configure()
        }
        AuthManager.shared.configure()
        _chatModel = State(initialValue: ChatModel())
    }

    /// The Info.plist is generated by Xcode (no UIAppFonts entry), so the
    /// bundled Libre Baskerville faces are registered at launch instead.
    private static func registerBundledFonts() {
        for name in ["LibreBaskerville", "LibreBaskerville-Italic", "Baskervville", "Baskervville-Italic"] {
            guard let url = Bundle.main.url(forResource: name, withExtension: "ttf")
                ?? Bundle.main.url(forResource: name, withExtension: "ttf", subdirectory: "Fonts")
            else {
                assertionFailure("Missing bundled font \(name).ttf")
                continue
            }
            CTFontManagerRegisterFontsForURL(url as CFURL, .process, nil)
        }
    }

    var body: some Scene {
        WindowGroup {
            ChatView()
                .environment(chatModel)
                .preferredColorScheme(.light)
        }
    }
}
