import SwiftUI
import CoreText
import FirebaseCore

@main
struct RecallTutorApp: App {
    @State private var chatModel: ChatModel
    @State private var hasCompletedOnboarding = UserDefaults.standard.bool(
        forKey: "recalltutor_has_completed_onboarding"
    )
    @Environment(\.scenePhase) private var scenePhase

    init() {
        Self.registerBundledFonts()
        // Firebase powers the built-in tutor (Google sign-in + managed Gemini).
        // Only configure when the app ships a GoogleService-Info.plist — the
        // app runs fine without it in bring-your-own-key mode (see FIREBASE.md).
        // Must happen before ChatModel() so provider detection sees Firebase.
        if Bundle.main.url(forResource: "GoogleService-Info", withExtension: "plist") != nil {
            FirebaseApp.configure()
        }
        AuthManager.shared.configure()
        _chatModel = State(initialValue: ChatModel())
    }

    /// The Info.plist is generated by Xcode (no UIAppFonts entry), so the
    /// bundled Libre Baskerville faces are registered at launch instead.
    private static func registerBundledFonts() {
        for name in ["LibreBaskerville", "LibreBaskerville-Italic", "Baskervville", "Baskervville-Italic"] {
            guard let url = Bundle.main.url(forResource: name, withExtension: "ttf")
                ?? Bundle.main.url(forResource: name, withExtension: "ttf", subdirectory: "Fonts")
            else {
                assertionFailure("Missing bundled font \(name).ttf")
                continue
            }
            CTFontManagerRegisterFontsForURL(url as CFURL, .process, nil)
        }
    }

    var body: some Scene {
        WindowGroup {
            if !hasCompletedOnboarding {
                OnboardingView(hasCompletedOnboarding: $hasCompletedOnboarding)
            } else {
                ChatView()
                    .environment(chatModel)
                    .preferredColorScheme(.light)
            }
        }
        // syncWithFirestore() otherwise only runs once at cold launch (via
        // AuthManager's auth-state listener) — a long-lived session that
        // uses the built-in tier on a second device meanwhile would drift
        // until the app is force-quit. Re-pull on every foreground instead.
        .onChange(of: scenePhase) { _, newPhase in
            guard newPhase == .active, AuthManager.isFirebaseConfigured, AuthManager.shared.isSignedIn else { return }
            Task { await SubscriptionManager.shared.syncWithFirestore() }
        }
    }
}
